# Generated by Django 4.1.7 on 2023-04-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_aluno_nome_alter_aluno_registro_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='registro_aluno',
        ),
    ]
